# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . ./app

# Install any needed packages specified in requirements.txt
RUN pip install -r app/requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run the app.py file when the container launches
CMD ["python", "app/app.py"]